apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-demo
  namespace: secure-app
spec:
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/secure-app/sa/default"]
